config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  
  resources :articles do
    resources :comments   #this is defined as subresource
  end

  resources :tags

  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments	#relation one to many : article has many comments. Comment belongs to one article
	has_many :taggings
	has_many :tags, through: :taggings
	# Many-to-many relationships are tricky because we’re using an SQL database. 
	# If an Article "has many" tags, then we would put the foreign key article_id inside the tags table - so then a Tag would "belong to" an Article. 
	# But a tag can connect to many articles, not just one. 
	# We can’t model this relationship with just the articles and tags tables.
	
	# Most of the time this isn’t the best way to really model the relationship. 
	# The connection between the two models usually has value of its own, so we should promote it to a real model. 
	# For our purposes, we’ll introduce a model named "Tagging" which is the connection between Articles and Tags. 
	# The relationships will setup like this:
	# 	An Article has_many Taggings
	# 	A Tag has_many Taggings
	# 	A Tagging belongs_to an Article and belongs_to a Tag

	# Now if we have an object like article we can just ask for article.tags or, 
	# conversely, if we have an object named tag we can ask for tag.articles.

	has_attached_file :image	
	# This has_attached_file method is part of the paperclip library. 
	# With that declaration, paperclip will understand that this model should accept a file attachment 
	# and that there are fields to store information about that file 
	# which start with image_ in this model’s database table.
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]


	def tag_list		#why we define the tag list here???
  		self.tags.collect do |tag|
    		tag.name
  		end.join(", ")		#end.join ?!?! WOW !!!
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  	new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		# go through each of those tag_names and find or create a tag with that name. Rails has a built in method to do just that (find_or_create_by)
  	self.tags = new_or_found_tags
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper	
		# params.require(:article).permit(:title, :body) is defined in app/helpers/articles_helper.rb

	before_filter :require_login, except: [:index, :show]

	def index
	  @articles = Article.all
	end

	def show
		@article = Article.find(params[:id])

		@comment = Comment.new	#adding new comment in show Article (different than Rails officila tutorial)
		@comment.article_id = @article.id

		#why we aren’t using @article.comments.new?
		#if we do so, there is an extra empty comment at the end of the list of comments. 
		#That is due to the fact that @article.comments.new has added the new Comment to the in-memory collection for the Article
	
	@article.view_count = @article.view_count.to_i + 1
	@article.save

	@view_count = @article.view_count

	@top_views = Article.order(view_count: :desc).take(3)		#sorting articles on view_count and take the first 3 records

	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		#replaced with the above, after defining article_params method in the articles_helper.rb
		#@article = Article.new(params[:article])
			# this is the equivalent of
			#		@article = Article.new(
    	#			title: params[:article][:title],
    	#			body: params[:article][:body])

		@article.save

		flash.notice = "Article '#{@article.title}' Created!"
  	# <p class="flash"><%= flash.notice %></p> added in the app/views/layouts/application.html.erb in order to apply to all views

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "Article '#{@article.title}' Deleted!"
  	# <p class="flash"><%= flash.notice %></p> added in the app/views/layouts/application.html.erb in order to apply to all views

		redirect_to articles_path
	end

	def edit
  	@article = Article.find(params[:id])
	end

	def update
	  @article = Article.find(params[:id])
  	@article.update(article_params)

  	flash.notice = "Article '#{@article.title}' Updated!"
  	# <p class="flash"><%= flash.notice %></p> added in the app/views/layouts/application.html.erb in order to apply to all views

  	redirect_to article_path(@article)
	end

	

end

app/helpers/articles_helper.rb
module ArticlesHelper
	private
		def article_params
	  	params.require(:article).permit(:title, :body, :view_count, :tag_list, :image)
		end
end

app/views/articles/_comment.html.erb
<div>
  <h5>Comment by <%= comment.author_name %></h5>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <!-- Rails has a really neat helper named distance_of_time_in_words which takes two dates and creates a text description of their difference like "32 minutes later", "3 months later", and so on. -->
  <br>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>    
<!-- html: {multipart: true} is needed to attach files -->

  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<!-- 
form_for is a Rails helper method which takes one parameter, in this case @article and a block with the form fields. 
The first line basically says "Create a form for the object named @article, refer to the form by the name "f" and add the following elements to the form…"
  The f.label helper creates an HTML label for a field. This is good usability practice and will have some other benefits for us later
  The f.text_field helper creates a single-line text box named title
  The f.text_area helper creates a multi-line text box named body
  The f.submit helper creates a button labeled "Create" 
-->

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
      				<!-- Note this si article_path, not articles_path -->
      				<!-- class and id are needed for CSSs -->
    </li>
  <% end %>
</ul>

<% if logged_in? %>
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>
<br>
<%= link_to "Show all Tags", tags_path, id: "show_all_tags" %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<br>
<h3>Article viewed <%= @view_count %> times </h3>
<br>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), id: "article_tags" %>
  <% end %>
</p>



<br>

<% if @article.image.exists? %>
    <%= image_tag @article.image.url %><br/>	<!-- Displays image only if exists (attached) -->
<% end %>

<br>

<p><%= @article.body %></p>
<p id="article_created_at">created at <%= @article.created_at %></p>

<br>

<p>

	<h2> Top articles on blog </h2>
	<ol>
		<% @top_views.each do |article| %>
			<li> 
				<%= link_to article.title + " with " + article.view_count.to_s + " views", article_path(article) %> 
			</li>
		<% end %>
	</ol>

</p>

<br>
<h3>Comments ( <%= @article.comments.size %> )</h3> 	<!-- the () are used just for display . eg: (5) -->

<%= render partial: 'articles/comment', collection: @article.comments %>
<!-- This renders a partial named "comment" and that we want to do it once for each element in the collection @article.comments. We saw in the console that when we call the .comments method on an article we’ll get back an array of its associated comment objects. This render line will pass each element of that array one at a time into the partial named "comment".  "collection" works somehow like 'comments.each' for the partial -->

<br>

<%= render partial: 'comments/form' %>

<br>
<%= link_to "<< Back to Articles List", articles_path %>
<br>
<br>
<% if logged_in? %>
	<%= link_to "Delete Article", article_path(@article), method: :delete, 
		data: {confirm: "Really delete the article?" } %>


<!-- The server is seeing a GET request, but the route needs a DELETE verb. How do we make our link trigger a DELETE?

You can’t, exactly. While most browsers support all four verbs, GET, PUT, POST, and DELETE, HTML links are always GET, and HTML forms only support GET and POST. So what are we to do?

Rails’ solution to this problem is to fake a DELETE verb. In your view template, you can add another attribute to the link like this: "method: :delete" -->

<br>
<br>
<%= link_to "Edit Article", edit_article_path(@article) %>

<% end %>