config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  
  resources :articles do
    resources :comments   #this is defined as subresource
  end

  resources :tags

  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

	get 'login'  => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_filter :require_login, only: [:destroy]

	def show
	  @tag = Tag.find(params[:id])
	end

	def index
		@tags = Tag.all
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		flash.notice = "Tag '#{@tag.name}' Deleted!"
  	# <p class="flash"><%= flash.notice %></p> added in the app/views/layouts/application.html.erb in order to apply to all views

		redirect_to tags_path
	end
	
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>

    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li style="font-weight: bold"><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<br>
<br>
<br>

<%= link_to "<< Back to Articles List", articles_path %>
<br>
<%= link_to "<< Back to Tags List", tags_path %>
<br>

<% if logged_in? %>

<%= link_to "Delete Tag", tag_path(@tag), method: :delete, 
	data: {confirm: "Really delete the tag?" } %>

<% end %>